# Generated by Django 3.2.4 on 2021-07-01 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='email_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peresnaluser',
            name='email_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peresnaluser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persenal_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
