# Generated by Django 3.2.4 on 2021-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20210701_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='email',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peresnaluser',
            name='email',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
