# Generated by Django 3.2.4 on 2021-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessuser', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('business_hour_start', models.CharField(max_length=32)),
                ('business_hour_end', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
