# Generated by Django 3.2.4 on 2021-07-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20210701_0901'),
        ('studycafe', '0003_studycafe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycafe',
            name='businessuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studycafe', to='userinfo.businessuser'),
        ),
    ]
