# Generated by Django 3.2.4 on 2021-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycafe', '0004_alter_studycafe_businessuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycafe',
            name='price_per_hour',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
